[theme]
primaryColor="#4A90E2"           # Muted blue for primary elements
backgroundColor="#1E1E2F"         # Dark background color
secondaryBackgroundColor="#2C2C3A" # Slightly lighter secondary background
textColor="#E0E0E0"               # Light text color for readability
font="sans serif"
